In [5]:
#for + operation

import numpy as np

arr1 = np.array([96,235,321])
arr2 = np.array([18,228,354])

result = arr1 + arr2
print(result)


[114 463 675]


In [7]:
#for - operation


import numpy as np

arr1 = np.array([8,17,27])
arr2 = np.array([1,10,20])

result = arr1 - arr2
print(result)


[7 7 7]


In [8]:
#for * operation


import numpy as np

arr1 = np.array([3,3,3])
arr2 = np.array([1,10,20])

result = arr1 * arr2
print(result)


[ 3 30 60]


In [11]:
#for / operation


import numpy as np

arr1 = np.array([3,3,3])
arr2 = np.array([1,10,20])

result = arr1 / arr2
print(result)

dt = result.dtype
print("The resultant Datatype is : ",dt)

[3.   0.3  0.15]
The resultant Datatype is :  float64
