In [7]:
#broad casting array
#use to change one or more than index's value at once

import numpy as np
arr = np.ones(16).reshape(4,4)
print("The old array is :\n",arr)

arr[0] = 200
print("The new array after broadcasting is :\n",arr)

arr[1] = 100
print("The new array after second time broadcasting :\n",arr)

The old array is :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
The new array after broadcasting is :
 [[200. 200. 200. 200.]
 [  1.   1.   1.   1.]
 [  1.   1.   1.   1.]
 [  1.   1.   1.   1.]]
The new array after second time broadcasting :
 [[200. 200. 200. 200.]
 [100. 100. 100. 100.]
 [  1.   1.   1.   1.]
 [  1.   1.   1.   1.]]
