In [3]:
#numpy.sum()
#uses to find out the sum of the array

import numpy as np
arr = np.array([1,2,3,4])
result = np.sum(arr)
print(result)

10


In [5]:
#numpy.mean()
#uses to find out the mean / গড় of the array

import numpy as numpy
arr = np.array([1,2,3,4,5,6,7,8,9])

result1 = np.sum(arr)
print(result1)
result = np.mean(arr)
print(result)

45
5.0


In [14]:
#numpy.max()
#use to findout the max of the array

import numpy as np
arr = np.array([12,4,5,78,96,100,58,56,28,97,8,5,88,5])
result = np.max(arr)
print(result)

100


In [15]:
#numpy.min()
#use to findout the min of the array

import numpy as np
arr = np.array([12,1,-6,25,98])
result = np.min(arr)
print(result)

-6


In [19]:
#numpy.argmax()
#uses to findout the max number's index of the array

import numpy as np
arr = np.random.randint(1,50,10)
print(arr)

res = np.max(arr)
print(res)

result = np.argmax(arr)
print(result)


[ 7 43 20 29 45 19  4 10 43 17]
45
4


In [39]:
#numpy.argmin()
#use to findout the small number's index from the array

import numpy as np
arr = np.random.randint(10,60,5)
print("The array is:",arr)

km = np.max(arr)
print("The Max element of the array : ",km)

kkm = np.argmax(arr)
print("The max element's index of the array :",kkm)

res = np.min(arr)
print("The Min element of the array : ",res)

result = np.argmin(arr)
print("The min element's index of the array :",result)

The array is: [56 35 50 11 48]
The Max element of the array :  56
The max element's index of the array : 0
The Min element of the array :  11
The min element's index of the array : 3


In [41]:
#numpy.sqrt()

import numpy as np
arr = np.arange(1,11,3)
print(arr)

result = np.sqrt(arr)
print(result)

[ 1  4  7 10]
[1.         2.         2.64575131 3.16227766]


In [43]:
#numpy.sin()
#use to fidn out the value of the sin's every element from the array

import numpy as np
arr = np.arange(1,11)
print(arr)

kh = np.sin(arr)
print(kh)

[ 1  2  3  4  5  6  7  8  9 10]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]


In [54]:
#numpy.std()
#it is a standard deviation function

#std() মূলত এই formula ব্যবহার করে:

#✅ Step 1: Mean বের করে
#✅ Step 2: প্রতিটা মান থেকে Mean বাদ দেয়
#✅ Step 3: square করে
#✅ Step 4: average নেয়
#✅ Step 5: square root নেয়


import numpy as np
arr = np.arange(1,50) #.reshape(7,7)
print(arr)

k = np.mean(arr)
print(k)

kh = np.std(arr)
print(kh)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]
25.0
14.142135623730951
