In [4]:
#size attributes

import numpy as np
arr = np.arange(1,15,2)
print(arr)

sz = arr.size
print("Array size: ",sz)

[ 1  3  5  7  9 11 13]
Array size:  7


In [9]:
#shape attributes

import numpy as np

arr = np.arange(16).reshape(4,4)
print(arr)

sp = arr.shape
print("The shape of the array is : ",sp)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
The shape of the array is :  (4, 4)


In [11]:
#ndim attributes

import numpy as np
arr = np.arange(16).reshape(4,4)
print(arr)

dim = arr.ndim
print("The dimension of the array is : ",dim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
The dimension of the array is :  2


In [13]:
#nbytes attributes

import numpy as np
arr = np.arange(16).reshape(4,4)
print(arr)

bt = arr.nbytes
print("The number of bytes in the array is : ",bt)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
The number of bytes in the array is :  128


In [15]:
#dtype attributes

import numpy as np
arr = np.arange(16).reshape(4,4)
print(arr)

dt = arr.dtype
print("The datatype of the array is : ",dt)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
The datatype of the array is :  int64
