In [28]:
#A dataframe Creating

import numpy as np

ind = ['r1','r2','r3','r4']
col = ['c1','c2','c3','c4']

arr = np.random.randint(1,100,16).reshape(4,4)

print(arr)

import pandas as pd
df = pd.DataFrame(data = arr , index = ind , columns=col)
print("The DataFrame is :\n",df)


#Select a columns from a DataFrame

print(df[['c1']]) #to execute a single columns
print(df[['c1','c2']]) #to execute multiple columns

print(df['c1']) #to know the name and  datatype  of a single columns


#select row from a data frame

print("The first row of the df is \n",df.loc[['r1']]) #to execute a single row
print(df.loc[['r1','r2']]) #to execute multiple rows

[[56 70 60 80]
 [25 67  2 40]
 [23 25 90 51]
 [40 64 57 27]]
The DataFrame is :
     c1  c2  c3  c4
r1  56  70  60  80
r2  25  67   2  40
r3  23  25  90  51
r4  40  64  57  27
    c1
r1  56
r2  25
r3  23
r4  40
    c1  c2
r1  56  70
r2  25  67
r3  23  25
r4  40  64
r1    56
r2    25
r3    23
r4    40
Name: c1, dtype: int64
The first row of the df is 
     c1  c2  c3  c4
r1  56  70  60  80
    c1  c2  c3  c4
r1  56  70  60  80
r2  25  67   2  40


In [39]:
#Implesite and Explisite index use to print the row terms

import numpy as np
import pandas as pd

ind = ['r1','r2','r3','r4']
col = ['c1','c2','c3','c4']

kh = np.arange(16).reshape(4,4)
print(kh)

df = pd.DataFrame(data = kh, index=ind , columns=col)
print(df)


print(df.loc[['r3']]) #to print with explisite index
print(df.iloc[['2']]) #to print with implisite index

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
    c1  c2  c3  c4
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15
    c1  c2  c3  c4
r3   8   9  10  11
    c1  c2  c3  c4
r3   8   9  10  11


In [63]:
#Row Selection using Conditions

import numpy as np
import pandas as pd


arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

k = arr.ndim
print("The dimension of the array is : ", k)
print(arr)


df=pd.DataFrame(data= arr, index=['R1','R2','R3'], columns=['A','B','C'])
print(df)

m = df.loc[df['A'] > 2] #using single condition #print those row where A is greater than 2
print(m)

#using multiple condition

n = df.loc[(df['A'] > 2) & (df['B'] > 5)]
print(n)

#using multiple condition and represt all of the array

o = df.loc[(df['A'] > 0) & (df['B'] > 1)]
print(o)


The dimension of the array is :  2
[[1 2 3]
 [4 5 6]
 [7 8 9]]
    A  B  C
R1  1  2  3
R2  4  5  6
R3  7  8  9
    A  B  C
R2  4  5  6
R3  7  8  9
    A  B  C
R3  7  8  9
    A  B  C
R1  1  2  3
R2  4  5  6
R3  7  8  9


In [85]:
#Using head() & tail() function

import numpy as np
import pandas as pd

ind = ['r1','r2','r3','r4','r5','r6','r7']
col = ['c1','c2','c3','c4','c5','c6','c7']

arr = np.arange(49).reshape(7,7)
print(arr)

df = pd.DataFrame(data = arr , index = ind , columns = col)
print(df)


#head() function
#total array holds 7 row and 7 columns then head function wil only executes thevery first 5 rows
#print(df.head())

print(df.head(2)) #to print first 2 row
print(df.head(1)) #to print first 1 row


#uses of tail() function
#total array holds 7 row and 7 columns then tail function wil only executes thevery last 5 rows

print(df.tail())
print(df.tail(2)) #to show exact last two rows form a df

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]]
    c1  c2  c3  c4  c5  c6  c7
r1   0   1   2   3   4   5   6
r2   7   8   9  10  11  12  13
r3  14  15  16  17  18  19  20
r4  21  22  23  24  25  26  27
r5  28  29  30  31  32  33  34
r6  35  36  37  38  39  40  41
r7  42  43  44  45  46  47  48
    c1  c2  c3  c4  c5  c6  c7
r1   0   1   2   3   4   5   6
r2   7   8   9  10  11  12  13
    c1  c2  c3  c4  c5  c6  c7
r1   0   1   2   3   4   5   6
    c1  c2  c3  c4  c5  c6  c7
r3  14  15  16  17  18  19  20
r4  21  22  23  24  25  26  27
r5  28  29  30  31  32  33  34
r6  35  36  37  38  39  40  41
r7  42  43  44  45  46  47  48
    c1  c2  c3  c4  c5  c6  c7
r6  35  36  37  38  39  40  41
r7  42  43  44  45  46  47  48
