For using Numpy Array function the syntax will be  arr.function (size) .reshape (row.num, col.num)

In [3]:
#numpy.zeros()

import numpy as np
arr = np.zeros(20).reshape(5,4)
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [2]:
#numpy.ones()

import numpy as np
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
#numpy.full()

import numpy as np
arr = np.full((4,3),45)
print(arr)

[[45 45 45]
 [45 45 45]
 [45 45 45]
 [45 45 45]]


In [10]:
#numpy.identity()

import numpy as np
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
#numpy.eye()
import numpy as np
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
#numpy.random.rand()

import numpy as np
arr = np.random.rand(3,2)
print(arr)

[[0.70207649 0.69808649]
 [0.8560838  0.7641809 ]
 [0.91057521 0.34433045]]


In [25]:
#numpy.random.randint()
import numpy as np
arr = np.random.randint(1,20,5)
print(arr)

#in this array , what is happened actually , here we gave the range 1 to 20 ,
#and then gave how much number we want from this range

[ 5 15 18  6  5]


In [34]:
#numpy.arrange()
#execution : numpy.arange(start,stop,step)

import numpy as np
arr1 = np.arange(10)
print(arr1)

arr2 = np.arange(11,30,2)
print(arr2)

binary_arr = np.arange(16 , dtype='int8')
print(binary_arr)

[0 1 2 3 4 5 6 7 8 9]
[11 13 15 17 19 21 23 25 27 29]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [39]:
#numpy.linspace()
#numpy.linspace(start , stop , num = 50, endpoint = True ,retstep = False , dtype = None, axis = 0)

import numpy as np
arr = np.linspace (0, 21 , 7 , retstep=True)
print(arr)

(array([ 0. ,  3.5,  7. , 10.5, 14. , 17.5, 21. ]), np.float64(3.5))


In [ ]:
#